# Generated by Django 5.1.4 on 2025-01-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('Babysitting', 'Babysitting'), ('Gardening', 'Gardening'), ('Tutoring', 'Tutoring'), ('Other', 'Other')], default='General', max_length=50),
            preserve_default=False,
        ),
    ]
