# Generated by Django 5.1.4 on 2025-01-09 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_alter_service_category_timetransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='hours_available',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timecredit',
            name='hours_available',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='timecredit',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.service'),
        ),
    ]
