# Generated by Django 5.1.4 on 2025-01-09 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_service_hours_available_timecredit_hours_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='hours_available',
        ),
        migrations.AlterField(
            model_name='timecredit',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.service'),
        ),
    ]
