# Generated by Django 5.1.4 on 2025-01-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0016_userlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
         migrations.AddField(
            model_name='timecredit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
