# Generated by Django 5.1.4 on 2025-01-26 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0017_service_location_servicerequest_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timecredit',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='timecredit',
            name='hours_available',
        ),
        migrations.RemoveField(
            model_name='timecredit',
            name='service',
        ),
        migrations.RemoveField(
            model_name='timecredit',
            name='user',
        ),
        migrations.AddField(
            model_name='timecredit',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='timecredit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timecredit',
            name='giver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='given_credits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timecredit',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_credits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_credits', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
