# Generated by Django 5.1.4 on 2025-01-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0018_remove_timecredit_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
