# Generated by Django 5.1.4 on 2025-01-26 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0019_userprofile_bio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timecredit',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='timecredit',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='timecredit',
            name='description',
        ),
        migrations.RemoveField(
            model_name='timecredit',
            name='giver',
        ),
        migrations.RemoveField(
            model_name='timecredit',
            name='receiver',
        ),
        migrations.AddField(
            model_name='timecredit',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='timecredit',
            name='hours_available',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='timecredit',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.service'),
        ),
        migrations.AddField(
            model_name='timecredit',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
