# Generated by Django 5.1.4 on 2025-01-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0023_servicelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='work_completed',
            field=models.BooleanField(default=False),
        ),
    ]
