# Generated by Django 5.1.4 on 2025-01-26 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0025_remove_servicelog_user_service_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicelog',
            old_name='provider',
            new_name='user',
        ),
    ]
