# Generated by Django 5.1.4 on 2025-02-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0026_rename_provider_servicelog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
