# Generated by Django 5.1.4 on 2025-02-02 11:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0028_remove_transaction_user_transaction_receiver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicelog',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='servicelog',
            name='service_date',
        ),
        migrations.RemoveField(
            model_name='servicelog',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='servicelog',
            name='user',
        ),
        migrations.AddField(
            model_name='servicelog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='servicelog',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_fulfilled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicelog',
            name='credits_earned',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicelog',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.servicerequest'),
        ),
        migrations.AlterField(
            model_name='servicelog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
