# Generated by Django 5.1.4 on 2025-02-22 12:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0030_remove_timecredit_hours_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecredit',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=10),
        ),
    ]
